### ISSUE TITLE
multi user/ multi calendar ?

### ISSUE THREAD

**Issue by abate** [arnowelzel/periodical#21]
Is there a way to track the period of multiple people ( polyamourous person here :) ) ?

**Comment by AlphaOmega3** [comment]
I concur!

(believe it or not, I logged in just to write it .. lol)

**Comment by c-key** [comment]
Hello, why is this rejected? I am a mother and it would be useful for me to track the period oft my childs. Is there a way to reactivate this issue? Thanks.

**Comment by arnowelzel** [comment]
Besides the neccessary effort and time to implement such a feature, the problem with this is that Periodical is intended for personal use and not to track your children. If your children have their period they should be old enough to use their own smartphones and do that on their own. The whole idea is that girls and women should be able to keep track of their own period and learn about their body.

However - since Periodical is Open Source everyone can participate and add this in an extended version of the app.
