### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [arnowelzel/periodical#29]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

1. Click on ...
2. Click on:
a. About...
b. Help
3. Scroll Down
4. Orientation Change

**Comment by arnowelzel** [comment]
I'm not sure if this behaviour can be fixed for several reasons:

1. These views are WebViews and there is no "clean" solution to save and restore the current scroll position.

2. It makes no sense to restore the absolute scroll position since then some different content may be visible anyway. In landscape orientation the text lines are longer therefore the same absolute position will show a diffent part of the content and it may even not be possible to move to the same position as it was in portrait orientation.
