### ISSUE TITLE
Problem when not info about 1 month

### ISSUE THREAD

**Issue by SenaidaHdez** [arnowelzel/periodical#55]
If there're some months you forget to add the day of your period, the automatic ovulation gets completely messy and it may even happen that it doesn't appear any region of ovulation at all. Or when you period is missed for a long period of time. I don't know if the estimation of the ovulation is correct in that case then. To give you an idea, apparently I have my period for 1 week (red), then I get 13days of ovulation (blue) and then I get 13 days of no ovulation (yellow). Or cases where the ovulation day (blue) is between yellow dats. I find this super weird and confusing. Maybe this could be fixed if the system only would take into account the last three months, for instance, to measure the ovulation probability.

**Comment by arnowelzel** [comment]
Well - if one forgets to add the day of the period, this is the logical result.

Solution: if you realize, that you forgot one day, just add it - problem solved.

There is no solution for this problem, since ovulation is just a calculated based on the given dates in the calendar:

Predicted day of ovulation = First predicted start of next period - Length of luteal phase
