### ISSUE TITLE
App does not seem to predict well.

### ISSUE THREAD

**Issue by SenaidaHdez** [arnowelzel/periodical#56]
I have a problem, because the app doesn't predict correctly in my case. First, I though it was because there were some missing data, so I erased those regions of missing data and I just included the period where the data is complete. That simply didn't work. It doesn't predict correctly. I am attaching 4 months with data, so it is possible to observe the error.

![periodicalsample-2018-07](https://user-images.githubusercontent.com/26250834/47876284-33d5d300-de19-11e8-9b4b-920c9d8502b4.jpg)
![periodicalsample-2018-08](https://user-images.githubusercontent.com/26250834/47876286-346e6980-de19-11e8-8f2f-c8e1dafba98b.jpg)
![periodicalsample-2018-09 jpg](https://user-images.githubusercontent.com/26250834/47876287-346e6980-de19-11e8-9db0-9e2b33432a40.jpg)
![periodicalsample-2018-10](https://user-images.githubusercontent.com/26250834/47876288-35070000-de19-11e8-8685-1be1c644e9c8.jpg)

**Comment by arnowelzel** [comment]
I'm sorry, but I'm not sure if I understand the problem.

Shortest cycle for October: 23 days
Longest cycle for October: 30 days

The calculation method, based on the assumption that the default luteal length of 14 in the settings wasn't changed:

The original Knaus Ogino method:

First fertile day in cycle = shortest cycle - 18 = 23 - 18 = 5
Last fertile day in cycle = longest cycle - 11 = 30 - 11 = 19

However, since there is the luteal length as well which may influence the cycle. Tthe luteal length is the event of the ovulation in number of days before the next period starts - e.g. the default of 14 means "ovulation is assumed 14 days before the next period starts".

First fertile day in cycle = shortest cycle - luteal length - 4 = 23 - 14 - 4 = 5
Last fertile day in cycle = longest cycle - luteal length + 3 = 30 - 14 + 3 = 19

Let's assume the luteal length was decreased to 12, so the ovulation is later, which will also move the fertility more to towards the end of the cycle:

First fertile day in cycle = shortest cycle - luteal length - 4 = 23 - 12 - 4 = 7
Last fertile day in cycle = longest cycle - luteal length + 3 = 30 - 12 + 3 = 21

Days marked as "period" override fertility, so day 5 and 6 are red. But day 7-20 in October are marked as "fertile". I'm not sure, why day 20 is also marked as "fertile", this maybe due to a comparison done with "<=" and not "<":

```
                            } else if (day >= this.cycleShortest - luteallength - 4
                                    && day <= this.cycleLongest - luteallength + 3) {
                                // Fertile days
```

**Comment by SenaidaHdez** [comment]
Thanks so much for the explanation! It is really nice!! Now I understand better how it works. So the fertile period is a big rough estimate, since the app predicts it is around 2 weeks of fertility.
