### ISSUE TITLE
Ovulation day

### ISSUE THREAD

**Issue by Sekhy2** [arnowelzel/periodical#67]
There is an issue with the ovulation day.
Its is actually :
Predicted day of ovulation = First predicted start of next period - Length of luteal phase
(as it is said in https://github.com/arnowelzel/periodical/issues/55)

But once users set the "real" day of the next cycle (period day), this day of ovulation should be updated to 1st day of next cycle - length of luteal phase.

This would not help for avoiding pregnancy, of course, since it is "too late", but it would really help understand what happened in the past cycle and link ovulation day with symptoms. Because some people have irregular cycles, that would be a huge help.

**Comment by arnowelzel** [comment]
This is already the case, see here:

https://github.com/arnowelzel/periodical/blob/master/app/src/main/java/de/arnowelzel/android/periodical/PeriodicalDatabase.java#L639

But to be honest I think about removing the ovulation, since this can not really be "calculated". The luteal phase can differ between 10 and 16 days and showing a fixed day for ovulation every cycle just based on a numeric parameter is just not correct.

**Comment by Sekhy2** [comment]
Sorry, I wasn't clear enough. I don't care about the prediction of the ovulation day (some users may use it, though, in the worst case you could put a checkbox in the options).

What I would like to see is the correct ovulation day, knowing the start of the next cycle. To understand *afterwards* that this day was ovulation (and link it with symptoms).

I'll give you an example.
In december, I had my period on the 10th. Giving the average of my cycle length (38 days), the ovulation was expected on the 3rd of January.
I finally had my period on the 10, so I know now that the ovulation was not on the 3rd of January, but on the 27th of december (14 days of luteal phase). But the app is still displaying a "O" on the 3rd of january, even after validating my period on the 10th.

Does it make sense now?

**Comment by arnowelzel** [comment]
I think the problem is, that the ovulation day is not calculated correctly. Even though I first said, the ovulation is depending on the end of the actual period length it is not :-(.

See https://github.com/arnowelzel/periodical/blob/master/app/src/main/java/de/arnowelzel/android/periodical/PeriodicalDatabase.java#L593

It's not the real end of the period which is used but only the average length. I think the fix might be just using `length` and not `average` at this point.

**Comment by Sekhy2** [comment]
Something like that, yes. 
If the length is known, use length. 
If length is not known (yet), use average.

Thanks a lot for your work!

**Comment by arnowelzel** [comment]
I think, that's the fix (https://github.com/arnowelzel/periodical/commit/3d173d0a86df9a2b5d33dbbd36c64376e4a2d4a1).

I just ran a quick test after that change with your example:

Period at December 10th with a predicted length of 39 days which results in an ovulation predicted at January 3rd:

<img src="https://user-images.githubusercontent.com/6613614/73313130-ac992a00-422a-11ea-8102-b6b6a05de323.png" width="320" height="569" /> <img src="https://user-images.githubusercontent.com/6613614/73313177-ccc8e900-422a-11ea-9122-2b591fbe1a66.png" width="320" height="569" />

And finally when setting January 10th as the real period start, the ovulation moves make to December:

<img src="https://user-images.githubusercontent.com/6613614/73313378-5a0c3d80-422b-11ea-8c8e-2b947e1ca88a.png" width="320" height="569" /> <img src="https://user-images.githubusercontent.com/6613614/73313455-950e7100-422b-11ea-8fab-9b91c1f9cb30.png" width="320" height="569" />
