### ISSUE TITLE
disappearing crash when restoring

### ISSUE THREAD

**Issue by HieronymusCH** [arnowelzel/periodical#73]
Periodical just disappears/crashes when I tap on "ok" for restoring the database.

Periodical 1.46
Samsung Galaxy a20e
SM-A202F/DS
Android 10

**Comment by arnowelzel** [comment]
The crash happens when trying to restore without an existing backup or if the selected location is the folder "de.arnowelzel.periodical" itself. One must always select the folder **above** this folder (for example the internal storage or SD card itself).

The crash was fixed with 477c79fa8f8e8616320d90cfb0803d277afe7357
