### ISSUE TITLE
Counter skips days, incorrect prediction

### ISSUE THREAD

**Issue by robertfalkenberg** [arnowelzel/periodical#97]
Thank you for maintaining this great application. Great work!

Version info: Periodical 1.71; Android 13

In a recent cycle, I noticed that the counter of the priod length was suddenly counting increments of two. See screenshot:
![image](https://github.com/arnowelzel/periodical/assets/86455551/5fa0f10a-3ea1-4af0-a6a4-c30374708813)

Removing the 11th and marking it again as start of the cycle, restores normal behaviour:
![image](https://github.com/arnowelzel/periodical/assets/86455551/7bf9a30a-dfbc-419d-8f57-aafb09d73f35)

I could not reproduce this, however I have backups of the DB before and after the Re-adding of the 11th, which I can provide as PM if needed.

This bug was the source of some confusion, since the user expects those counters to work correctly (the human eye won't even notice at first glance). The next cycle is "silently" predicted 3 days earlier, so you are supposedly too late...

**Comment by arnowelzel** [comment]
Thanks for the offer. Yes having a copy of the DB would help a lot to sort this out.

**Comment by robertfalkenberg** [comment]
Hi Arno,
thank you for having a look into it.
I have uploaded the backups from before and re-adding to your Nextcloud as `periodical-issue-97.zip`.

Please let me know if you need further information.

**Comment by arnowelzel** [comment]
Thanks, I am traveling at the moment and may look into it tomorrow or Tuesday.

**Comment by arnowelzel** [comment]
The reason for this effect is as following:

The database two records with the following event dates which I can clearly see in an SQLite database editor:

```
20230511
20230512
20230512
20230513
20230513
20230514
20230514
```

So `20230512`, `20230513` and `20230514` are repeated twice which causes the error the day of cycle count.

I don't know how this happened - technically this should not be possible at all since if there is already an existing record for a day it will only get updated but no records will be added for the same day. Maybe this was caused by a bug in an earlier release, but I am not aware of any bug like that.

The reason why this gets fixed when editing the entries is, that the records for that cycle will then be updated in a way to make sure each day only exist once.

I will add a check to make in the database handler to make sure that duplicate records will be ignored if they exist, so this should never happen again.

**Comment by robertfalkenberg** [comment]
Great work! Thanks for fixing this so quickly.
